### ISSUE TITLE
 Why not generate MP3 files?

### ISSUE THREAD

**Issue by 12366** [dooboolab/flutter_sound#19]

**Comment by 12366** [comment]
I am creating an app that contains voice recording and playing. Is it possible to record files in MP3 format

**Comment by hyochan** [comment]
Hm question on the thumb up on first written issue. Yeah, we can support mp3 format but that should take some time testing especially for android because it isn't primarily supported format in android. It is same as in `ios` but `ios`, it is better because there is only one `manufacturer`.

This is an opensource, and I've just provided what I've been using so far. If there are more features you want to include, please give any `PR` then I can look and work with your idea.

**Comment by venuxvg** [comment]
I have tried this and it is working fine.     
 String path = await flutterSound.startRecorder('/storage/emulated/0/default.mp3');
