### ISSUE TITLE
ffmpeg getLastCommandOutput

### ISSUE THREAD

**Issue by tonypottera24** [dooboolab/flutter_sound#244]
### Version of flutter_sound
`flutter_sound: ^2.1.1`

I'm planning to get the duration of an audio file.
The only way I can get the duration by `flutter_sound` is to `startPlayer` and listen to the `onPlayerStateChanged`.

Days after, I found out that `flutter_sound` provides an api called `executeFFmpegWithArguments`. 

It might be possible to get the duration by `ffmpeg -i file.aac`.

However, `flutter_sound` lacks the `getLastCommandOutput` api ( which was provided by `flutter_ffmpeg`) to get the command line output.

**Comment by Larpoux** [comment]
This `issue` is very interesting.
When I included ffmpeg as a flutter_sound dependency, I was sure that ffmpeg will open doors to many improvements.
Actually I have not much time . But I definitely want to look to this issue deeper later

**Comment by Larpoux** [comment]
@tonypottera24 : 
I agree with you : having an API verb to execute FFmpeg, but no way to get the result was stupid. I just added two API verb in the beta branch of flauto 3.0.1 (a flutter_sound branch) : 
- getLastFFmpegReturnCode()
- getLastFFmpegCommandOutput()

Now some remarks : 
1. `executeFFmpegWithArguments` was not supposed to be called by the App developper. I use internally this function to record/play OGG/OPUS on iOS. I just declared this API verb public because I did not see any reason to keep it private.

2. I am not satisfied that flutter_sound/flauto is an intermediate between flutter_ffmpeg and the App Developer. If the App Developer needs to use the ffmpeg tools, he/she would be able to call flutter_ffmpeg without flutter_sound.

3. Actually, I am not sure that it is possible for the App Developper to call directly flutter_ffmpeg because flutter_sound/flauto already open a flutter channel to flutter_ffmpeg. This need to be checked.

4. Not good to begin adding verbs in flutter_sound as interface to flutter_ffmpeg. At the end, we will get the complete flutter_ffmpeg API inside flutter_sound. Definitely not good.

5. I added the API verb `executeFFmpegWithArguments` inside flutter_sound as a way for the App Developer not to be forced to link his/her App with flutter_ffmpeg. But I think, now, that FFmpeg is so powerful that it is OK that version 3.x will depend on flutter_ffmpeg

6. An API verb to get a sound duration is certainly missing. probably this verb will call FFmpeg, but this should not be seen by the App Developper.

@hyochan is actually very, very busy for flutter_sound maintenance.
In the interim I suggest that you use the `flauto` fork, and verify that your needs are fulfilled.

The sources [are here](https://github.com/Canardoux/flauto).
- branch `stable` is the actual flutter_sound (V 2.1.1)
- branch `beta` is the new plugin with advance features (V 3.0.1)
- branch `master` is just for the project development and not to be used.

The flauto plugin is published. In your pub spec.yaml : 
```
dependencies:
  flutter:
    sdk: flutter
  flauto: ^3.0.1+1
```

**Comment by hyochan** [comment]
I've managed to release `flauto` today in `3.0.0`. Will this issue be fixed?

**Comment by tonypottera24** [comment]
@Larpoux Thank you for your help.
I think maybe `flutter_sound` should act like a wrapper and provide API for common audio related usages. 
For example, the audio properties such as duration, bitrate, format, ... in `FlutterFFprobe` section.

https://github.com/tanersener/flutter-ffmpeg#3-using

But I'm little bit confused to the future of `flutter_sound`, and cannot find the explanation in README.

1. Will `flauto` replace `flutter_sound` eventually?
2. What is the main difference between `flutter_sound` and `flauto`, why changing names?

**Comment by hyochan** [comment]
There was quite a large feature that may cause breaking changes and @Larpoux has given a code name which is `flauto`. It's been merged to `3.0.0` and we can use it now.

**Comment by tonypottera24** [comment]
Thank you for the explanation and contribution.
I think this issue can be closed.

**Comment by Larpoux** [comment]
> think maybe `flutter_sound` should act like a wrapper and provide API for common audio related usages.
> For example, the audio properties such as duration, bitrate, format, ... in `FlutterFFprobe` section.

Hi @tonypottera24 ,
flutter_sound beta version 3.1.1 embeds a few verbs to call flutter_ffmpeg : 
- FlutterSoundHelper.FFmpegGetMediaInformation(_<A_file_path>_);
- FlutterSoundHelper.duration(_<A_file_path>_)

This version is beta and not yet merged with flutter_sound Master branch.
But you can test it on : https://github.com/Canardoux/flauto

**Comment by tonypottera24** [comment]
Wow! thanks a lot!
Looking forward to the release.
