### ISSUE TITLE
app size after release

### ISSUE THREAD

**Issue by hatemragab** [dooboolab/flutter_sound#291]
Version of flutter_sound 3.1.8

 app size after release when add flutter_sound plugin very big!  how can I reduce app size

**Comment by laoluibitoye** [comment]
I have a similar issue, my app size tripled after adding the flutter_sound plugin. Is there any workaround to this?

**Comment by Larpoux** [comment]
This is bad. We must investigate why. Flutter Sound should be very small and light.

**Comment by hatemragab** [comment]
![image](https://user-images.githubusercontent.com/37384769/79367878-d66f0c80-7f4e-11ea-8aba-dc5fb39ef2a7.png)

**Comment by hatemragab** [comment]
> This is bad. We must investigate why. Flutter Sound should be very small and light.

you can create a new flutter project and just app flutter_sound and try to release the app

**Comment by hatemragab** [comment]
this error appeared from version 3.0.0 and above

**Comment by hatemragab** [comment]
is there any updates?

**Comment by noobcoder17** [comment]
I just created a new Flutter project , added the flutter_sound package, then build an apk in release mode. Size of the apk is 46.5 MB.

**Comment by hatemragab** [comment]
> I just created a new Flutter project , added the flutter_sound package, then build an apk in release mode. Size of the apk is 46.5 MB.

wow new app must less than 20 MB

**Comment by Larpoux** [comment]
It should be possible, I think, to maintain a strip down version of Flutter Sound, which does only playback and does not support OGG/OPUS playback on iOS.

But this would add some work on the maintenance side. Is it really something like that, that you want, you, the App developers ?

**Comment by noobcoder17** [comment]
Please make two seperate packages. I don't think it will be a difficult
task for you. Developers may need only the audio player features. In that
case by importing this whole flutter_sound package, they really don't want
to increase the app size. Please make two seperate packages. We love your
work.

Akash Debnath

**Comment by Larpoux** [comment]
@hyochan  ? What is your point of view ?

**Comment by Larpoux** [comment]
@noobcoder17  : 
If really we maintain a `flutter_sound-light` version, will this light version support `TrackPlayer` (the possibility to control flutter_sound from the lock screen) ?
`TrackPlayer` is probably the other place where flutter_sound get its weight.

**Comment by noobcoder17** [comment]
Yes , we need Track Player in the light version.

Akash Debnath

**Comment by Larpoux** [comment]
Something that I loved with the Flutter Sound project, was that it was light and simple.
but there are two categories of developers who use `Flutter Sound``` : 
- Those who need many functionalities. For example the possibility to use `Flutter Sound` for Speech to Text, record MP3, control Flutter Sound from an Apple watch, ...
- Those who need a very simple and light product.

Maintaining a light version will have a real impact on the maintenance load. Probably much. But it would have some benefit aspects.

**Comment by Larpoux** [comment]
@noobcoder17 : could you live without `Track Player` ?
We cannot maintain 12 versions of Flutter Sound.
Some other developers will say that they are not interested in `Track Player` and want a really light tool.

**Comment by noobcoder17** [comment]
I think there are two main functions of this package. One is to play sonds
and other is to record sond. I am just asking to separate those two
functionality if you can. But if it's hard to maintain , then make a
lighter version as you wish so that our app size is minimised. Thanks.

Akash Debnath

**Comment by Larpoux** [comment]
OK, I will think about that.
In every case, we must wait for a green traffic light signal from @hyochan : this is a major design choice.

**Comment by Larpoux** [comment]
Because I am in charge of Flutter Sound maintenance, I see another benefit aspect with a light version : this version would be very less buggy.
I must confess that I worry a little bit with the `Track Player` maintenance.

**Comment by srihariash999** [comment]
@Larpoux I recently started building a podcast client using Flutter sound, so the TrackPlayer Feature was kind of essential. But, seeing this now, 100 mb+ podcast client will be useless. Is there a way to strip the recorder features completely and just keep trackplayer features intact? Will that be a very hassle-included modification?

**Comment by Larpoux** [comment]
I think the answer is yes. If a majority of App developers really want Track Player, it is possible to keep it in a light version of flutter_sound.
In any case must wait for the green traffic light from @hyochan .

**Comment by Larpoux** [comment]
> strip the recorder features completely and just keep trackplayer features intact?

No, it will not be intact. OGG/OPUS playback on iOS, for example, would not be possible anymore.

**Comment by srihariash999** [comment]
OGG/OPUS thankfully is not a problem for me, I mainly deal with mp3 files most of the time. Main reason for choosing the flutter_sound for me was the lockscreen and notification shade player. And the way we can show the details in those easily.

**Comment by Larpoux** [comment]
😆 .
Thank you for your feedback. We definitely need to understand what Flutter Sound is used for, so that we can organize the priorities.
We have many, many things in the pipe-line. Too many for my taste.

**Comment by srihariash999** [comment]
I built my app which currently just has two screens and uses only flutter_sound to verify if it is actually big. Thee release version is 50~ MB. It is definitely heavy. Is that 'needs more investigation' tag for the confirmation of this issue?

**Comment by Larpoux** [comment]
'needs more investigation' tag is because we must locate what is the reason of this size.
I really think it is caused by `mobile_ffmpeg`, but we must double-check this supposition.
It would be stupid to do major developments, and realize after finished that the size has not decreased substantially.

**Comment by hatemragab** [comment]
I think flutter_sound_record and flutter_sound_player will be great

**Comment by hyochan** [comment]
> I think flutter_sound_record and flutter_sound_player will be great

Well, in this case, there is already a library.
[audio_recorder](https://github.com/ZaraclaJ/audio_recorder) and [audio_player](https://github.com/hui-z/audio_player).

For ease of maintenance, I've chosen to put them in once place since they meaninglessly affects sizes of the app. I still can't find a specific reason why they should be separated. It is even better to handle both threads in such scenarios like when you want to pause the player before recording (we can handle such issues like this inside the plugin and not leaving them for developers).

I still think they should interact nicely with each other in one place although some of them might only need `recorder` or `player` and that's why I've even made the plugin name `flutter_sound` (do both). Yes, and they can also interact in separate plugins but I confidently suspect that there may be a hole in maintenance at some point (I just don't want this to happen).

If we have a bigger team to maintain `flutter_sound`, we can have the below scenario.
1. flutter_sound_recorder
2. flutter_sound_player
3. fluter_sound_combine (Depends on the above plugins and do interactive stuff as explained)
4. flutter_sound_combine_ffmpeg (Depends on `flutter_sound_combine` and `ffmpeg`)
5. flutter_sound_recorder_lite (Anything that can be slimed down from `flutter_sound_recorder`. `flutter_sound_recorder` may have it as a dependant)
6. flutter_sound_player_lite (Anything that can be slimed down from `flutter_player`. `flutter_sound_player` may have it as a dependant)
7. flutter_sound_combine_lite (Depends of `flutter_sound_recorder_lite` and `flutter_sound_player_lite`)
...

I think we can separate them like above when we think this plugin is mature enough for all cases. Before that, we need to make our team sizes bigger and have volunteers to work on separate plugins as listed above (I think we need sponsor then).

Currently, focusing on feasibility, I think we can improve our plugin with `flutter_sound` and `flutter_sound_lite` (without FFmpeg that removes `flauto` feature). I am quite sure the sizes matter if `ffmpeg`.

@Larpoux What's your opinion?

**Comment by Larpoux** [comment]
Yes, Hyo
I totally agree with you. Flutter Sound Lite must support everything same than Flutter Sound Full, except that it will not have mobile_ffmpeg embedded.
`flauto` feature does not depend onf `ffmpeg`.

I am going to implement this new plugin, now.
(if I have some time left by the 3.1.x maintenance. Actually, 3.1.x request much of my time. This is too much for my taste).

When I will have finished this development, you will check if it is OK for you.

**Comment by Larpoux** [comment]
OK, guys and girls,

I did some measurements : 

1. When we build the example(demo) app with the actual full flavor of flutter_sound (with ffmpeg embedded) : 
- iOS -> 15 mega-octets
- Android apk -> 58 mega-octets

2. When I link with the future lite flavor of flutter_sound (without ffmpeg)
- iOS : 239 kilo-octets
- Android apk : 18 mega-octets

**Comment by Larpoux** [comment]
hi, guys and girls,

Could you try `flutter_sound_lite 4.0.0-beta.3` and tell us if this is OK for you ?

Re-open this issue if you think that this point is not correctly handled by this new Flutter Plugin.

**Comment by Dorbmon** [comment]
> hi, guys and girls,
> 
> Could you try `flutter_sound_lite 4.0.0-beta.3` and tell us if this is OK for you ?
> 
> Re-open this issue if you think that this point is not correctly handled by this new Flutter Plugin.

Thank you.You saved me haha.

**Comment by FilledStacks** [comment]
@Larpoux do you think we can apply [this](https://stackoverflow.com/a/22900048) . I'm trying to figure out where the ./configure file should go

**Comment by Larpoux** [comment]
Actually, the native code (java and Objective C) are directly linked with `mobile-ffmpeg-audio`.
I did not want to bother with a ./configure.
But probably possible. This is great if you can investigate what is possible for Flutter Sound.
