### ISSUE TITLE
How to track if player is paused from notification shade?

### ISSUE THREAD

**Issue by srihariash999** [dooboolab/flutter_sound#314]
### Version of flutter_sound
  3.1.0
### Platforms you faced the error (IOS or Android or both?)
     android

I can't figure out how to change the state of my UI if the playback is paused from the lockscreen or the notification shade. Is there any callback when these buttons are pressed? I can't find them in the docs.

I subscribed to the onPlayerStateChanged subscription, it is working fine if I pause it from my UI, but doesn't provide anything when paused from the notification shade.

Also, how to use the 'whenPaused' porperty in the TrackPlayer? Will that be of any help?

**Comment by Larpoux** [comment]
Oh ! 👎 
It seems that the parameter `whenPaused,:` is missing in the documentation.
This documentation really must be improved.

When the App does not specify this parameter, then Flutter Sound just pause the playback.
But if the App specify a call back, then Flutter Sound will trigger the callback and will not pause itself.
```
startPlayerFromTrack
(
      ....
      whenPaused: (){ doSomething; },
);
```
Please keep this issue open, so that someone will fix the documentation.

**Comment by srihariash999** [comment]
I tried doing this,:

`whenPaused: (){
 print("something");}`

But I got an error saying:

> The argument type 'Null Function()' can't be assigned to the parameter type 'void Function(bool)'  

So i changed the code to :

```
whenPaused: func(),

...

func () 
{ print("something"); }
```

Still, when I press the pause button from the notification screen, nothing prints. Also, strangely, the something gets printed once, when the player is stopped initially and starts to play. Am I doing something wrong?

**Comment by Larpoux** [comment]
@srihariash999 ,
I am sorry that you lost time on this issue.
I looked to Flutter Sound and it seems that `onPaused:` is not completely implemented in Flutter Sound. This is probably the reason that this parameter was not documented.
I consider this issue as a serious bug that we must fix.
I am going to work and will publish a fix in Version 3.1.11 (probably in a few days).

Again, sorry that you have spent time on this issue.

**Comment by srihariash999** [comment]
Its alright. Thank you for your fast response. Waiting for the release 🙌

**Comment by bsutton** [comment]
I do have a fix for this in the 5.0 release.

**Comment by srihariash999** [comment]
@bsutton  where can I find the 5.0 release? I don't see it in pub.dev release page, even in beta versions. Also, I'm not sure that everything else will work fine if I change the whole package to another version, perhaps my safest bet is to wait for @Larpoux  to release a version with a fix for this bug.

**Comment by Larpoux** [comment]
Maintenance of released version is a priority : Dev, is always only after maintenance.
@bsutton : you should suggest a patch for 3.x . Or better on 4.0.
Il will release 4.0 tomorrow or Saturday, and I really would like that this issue will be fixed then.
Version 5.0 is not actuality. 

Note : I would like also that the crash in TrackPlayer when the module is not completely initialized be fixed in this version. If you have a patch to offer I will be grateful.

**Comment by bsutton** [comment]
It hasn't been pushed as yet. Hopefully will get pushed to pub Dev on the
next few days

**Comment by bsutton** [comment]
The patch would be non trivial as it was part of the reachitecture.

I will have a look to see what is possible but I'm not optimistic.

**Comment by Larpoux** [comment]
OK, flutter_sound V4.0.0 has been just released.
There is a new parameter to `startPlayerFromTrack()` : `whenPaused:`.
Please refer to the README to have informations on this parameter.

Please, re-open this issue if this is not a correc answer to your needs.

**Comment by srihariash999** [comment]
Thank you very much @Larpoux. I tried it in the way shown in the docs and it works like a charm.

**Comment by Larpoux** [comment]
**YEAH!!!!!** :
I like when things works fine. (Not very often unfortunately)
Thank you for your comment.
It makes be better. Maintenance is some time something very hard for self confidence.
