### ISSUE TITLE
Abstract iosSetCategory/androidAudioFocus

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#326]
We have a couple of OS specific api's exposed in the public api.

Ideally the public api should not expose any OS specific api calls but rather provide an abstracted set of calls.

I don't fully understand what iosSetCategory does so I'm not quite certain what needs to be changed.

@Larpoux can you provide any guidance on this?

**Comment by Larpoux** [comment]
> Ideally the public api should not expose any OS specific api calls but rather provide an abstracted set of calls.


Yes, I totally agree. In a future version we must find high level concept (for example Duck Others), and allow the app to specify what he wants to do with those concepts.

Actually, `StartRecorder()` has optional parameters for iOS and for Android. This is not good, because those parameters conflicts whith the 'Codec` parameter which is OS independent.

Unfortunately, some features are offered in one OS but not in the other. And the App could want to handle those features directly, using Flutter Sound.

My thinking is that high level API verbs (`initialize()`, `startRecorder()`, `Duck Others`, must be OS independent, but we can also offer new low level verbs for users wanting to tweak directly their App.

**Comment by chandlery54** [comment]
I have wondered about these specific calls as well. 

I am actually looking to turn off the Automatic Gain Control (AGC) so that I can measure specific dB readings and recognize loud noises. But the AGC settings are stopping me from getting accurate readings. Looking into doing this has pointed me to setting the iOS `AVAudioSession.Category` to `record` (or `playAndRecord`) and set the `AVAudioSession.Mode` to `measurement` in iOS. It seems like this might be possible with the `iosSetCategory` call, but is not seeming to accomplish what I'd like. 

I'm still working on figuring out how to do this on Android as well. But would love to know if this is possible with flutter_sound or not. Or even if you know how to do this otherwise? 

If it's possible to turn off AGC and set the gain to a fixed level (very low in my case) that would be great!

**Comment by Larpoux** [comment]
iosSetCategory() is a direct call to the iOS function.
Because I did not know very well what this iOS function was used for, I prefered to offer all the parameters to the App, without hiding any possibility.
You are now confirming that I was right. 
And probably other verbs will be needed too.

Same for androidAudioFocus. But for this verb I am not completely sure that it is not possible to hide the call behind high level concepts like "Request Audio Focus and stop/duck/keep others"

**Comment by Larpoux** [comment]
> If it's possible to turn off AGC and set the gain to a fixed level (very low in my case) that would be great!

I am not an audio specialist, and I do not master that. Perhaps someone else can answer to @chandlery54 ?

**Comment by Larpoux** [comment]
@chandlery54 : I am just a simple developer. I develop many things that I do not master at all. Actually I am currently working on an App to learn Korean, but I do not know Korean, even just one word!
To develop, I just need specs from my *"customer"*.
If you give me specs, I will certainly try to fulfill  your needs with Flutter Sound.

(Specs = functional specifications)
