### ISSUE TITLE
macos support?

### ISSUE THREAD

**Issue by erf** [dooboolab/flutter_sound#332]
do you plan macOS support?

**Comment by Larpoux** [comment]
We envisage that, because **Macos** should not too different than ios.
But we have limited human resources and we will probably look to a **Web** support before.
Nothing is really planed today.

**Comment by matthiasn** [comment]
@Larpoux do you think there's a chance you might revisit macos support? I saw you added a folder `flutter_sound_macos` with a TODO in the meantime. Thanks a lot 🙏

**Comment by ihorkozar** [comment]
Any updates ?

**Comment by Larpoux** [comment]
Actually I am working on Flutter Sound 10.0
I do not plan to do improvements in 9.x.
Flutter Sound 10.x will support the 3 majors desktop (macOS, linux and windows).
But do not expect a 10.0 release soon : this release will need much work and I am a little bit slow to develop it.

**Comment by mminhlequang** [comment]
+1 upvote

**Comment by Larpoux** [comment]
Ok. I will work on that.
Actually I have stopped working on 10.0, because this is too much work.
I will release 9.20.0 in a few days. This will support PCM FLOAT32 on iOS, with a number of channels >= 1
Then I will work on 9.21.0, that will support Record to stream and playback from streams on web.
Then, If I don’t encounter new priorities, I could work on macOS. This is a dev that I would like to do, but I don’t promise anything.
