### ISSUE TITLE
[HELP] Is this library able to stream audio?

### ISSUE THREAD

**Issue by claudemirAvelino** [dooboolab/flutter_sound#346]
i would like help if with this library i can stream audio. I am doing a project for the college aimed at the visually impaired so that they can participate in theaters and shows. I need to capture the audio and transmit over the network. I'm looking for a library that can help me do this kind of action. Can this library help me?

**Comment by Larpoux** [comment]
Streaming audio is probably the first thing we have on top of our list TODO.
What I would like to stream the input Audio to a Dart Stream instead of a file.
I began to look to what can be done, but my actual conclusion is that it is not so simple.

Please keep this issue open. I really want to find a way to offer this feature in Flutter Sound.

**Comment by Larpoux** [comment]
I am working on this issue.
I hope to be able to release something in next version 6.0.
Please keep this issue open.

**Comment by Larpoux** [comment]
V6.0 is released. With this version we can record PCM-LINEAR-16 to a Dart Stream or Playback a PCM-LINEAR-16 from a Dart Stream.

**Comment by canitez** [comment]
> V6.0 is released. With this version we can record PCM-LINEAR-16 to a Dart Stream or Playback a PCM-LINEAR-16 from a Dart Stream.

Is the source of this stream the microphone? Or can it get sound from any application playing on the screen?
