### ISSUE TITLE
[BUG] Calling closeAudioSession throws a platform exception

### ISSUE THREAD

**Issue by chi-tea-72** [dooboolab/flutter_sound#370]
## Flutter Sound Version : 

- **Released** or **Beta** version ? Released

- Version number ? 5.0.1

- **FULL** or **LITE** flavor ? LITE

- Result of the command **"flutter pub deps | grep flutter_sound"**
(important)

----------------------------------------------------------

## Severity

Halts code execution. Unable to get past the following line in my code to execute code afterwards: 
`await _audioRecorder.closeAudioSession();`

--------------------------------------------------------

## Platforms you faced the error 

A real android device.

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)
`E/MethodChannel#com.dooboolab.flutter_sound_recorder(24648): Failed to handle method call
E/MethodChannel#com.dooboolab.flutter_sound_recorder(24648): java.lang.NullPointerException: Attempt to invoke interface method 'void com.dooboolab.fluttersound.RecorderInterface._stopRecorder()' on a null object reference`

From the stack trace we start here:
https://github.com/dooboolab/flutter_sound/blob/master/lib/src/flutter_sound_recorder.dart#L144
Finally the crash occurs here: https://github.com/dooboolab/flutter_sound/blob/master/lib/src/session.dart#L51

------------------------------------------------

**Describe the bug**
Calling `await recorder.closeAudioSession()` triggers a Platform exception to be thrown. The exception is `void com.dooboolab.fluttersound.RecorderInterface._stopRecorder()' on a null object reference`. This happens even when I move the method call to dispose().

**Expected behavior**
I expect calling `await recorder.closeAudioSession()` to simply clean up the audio resources, and not throw an exception.

-----------------------------------------------------------------

**Comment by Larpoux** [comment]
Fixed in Pull Request #371 : 
```closeRecorder```  is supposed to always work without throwing any exception.
This verb was not correctly protected on Android.

**Comment by chi-tea-72** [comment]
Thank you @Larpoux! When can we expect it to be merged to master?

**Comment by Larpoux** [comment]
Is that branch better ?

**Comment by chi-tea-72** [comment]
Ok I'll try it out and let you know asap

**Comment by chi-tea-72** [comment]
Hi @Larpoux, I just pulled in that branch and tested it, it didn't throw any errors so looks good to me!

**Comment by chi-tea-72** [comment]
Do you think it's better to call it in dispose() or before dispose happens. I tested it in both cases and it worked fine, but is there a preferred location to call it from, or does it not matter?

**Comment by Larpoux** [comment]
It does not matter. Probably during dispose() is convenient.

**Comment by cristoj** [comment]
Somebody kenows when will be this fix publicated in https://pub.dev/??? Thanks a lot.

**Comment by Larpoux** [comment]
I am currently workin on FS 5.1.0 .

I hope to publish it later this week.

**Comment by Teka-coder** [comment]
The method 'closeAudioSession' isn't defined for the type 'FlutterSoundRecorder'.
Try correcting the name to the name of an existing method, or defining a method named 'closeAudioSession'.dart[undefined_method](https://dart.dev/diagnostics/undefined_method)
Type: InvalidType

**Comment by Teka-coder** [comment]
Because flutter_sound >=9.8.1 depends on flutter_sound_web 9.8.1 which depends on js ^0.7.1, flutter_sound >=9.8.1 requires js ^0.7.1.
Because flutter_secure_storage_web 1.2.1 depends on js ^0.6.3 and no versions of flutter_secure_storage_web match >1.2.1 <2.0.0, flutter_secure_storage_web ^1.2.1 requires js ^0.6.3.
Thus, flutter_sound >=9.8.1 is incompatible with flutter_secure_storage_web ^1.2.1.
And because flutter_secure_storage 9.2.2 depends on flutter_secure_storage_web ^1.2.1 and no versions of flutter_secure_storage match >9.2.2 <10.0.0, flutter_sound >=9.8.1 is incompatible with flutter_secure_storage ^9.2.2.
So, because customer_app depends on both flutter_secure_storage ^9.2.2 and flutter_sound ^9.8.1, version solving failed.

**Comment by Larpoux** [comment]
@Teka-coder : it seems that  flutter_secure_storage_web 1.2.1 depends on js ^0.6.3, which is an old version of JS.
I would not like to have to downgrade Flutter Sound to be compatible with this JS version, because others Flutter Sound users could complain that our plugin uses a too old JS version.

It would be better if `flutter_secure_storage_web` uses a more recent version of JS.
What can we do ? What do you suggest ?

**Comment by Larpoux** [comment]
Flutter Secure Storage Web 2.0.0-beta-1 does not depend anymore on JS.
Maybe you can consider using this version of Secure Storage Web ?
