### ISSUE TITLE
[HELP] Record and playback pcm raw for both android and ios

### ISSUE THREAD

**Issue by chi-tea-72** [dooboolab/flutter_sound#394]
## Here is my question :
What does the timeline look like to support pcm raw on IOS for recording and playback?

According to the codecs chart, android already has pcm raw support, but not ios: https://github.com/dooboolab/flutter_sound/blob/master/doc/codec.md#actually-the-following-codecs-are-supported-by-flutter_sound

However, IOS has pcm wav support. Does that mean the header info just needs to not be included for IOS to have pcm raw support.

**Comment by chi-tea-72** [comment]
I think I may be okay with just using pcm wav

**Comment by Larpoux** [comment]
Actually RAW-PCM is not very useful.
We really need the Wave header to get the sample-rate and others parameters to play PCM.

RAW PCM is almost for future developments. It will be used later to push the raw data in a Dart Stream instead of writing to a file. Unfortunately actually I was not able to implement this for ios. 
I will work on this later (actually I am very busy).
Or perhaps someone else could work on this ? (We really need contributors for Flutter Sound developments)

**Comment by chi-tea-72** [comment]
I actually think the stream would be one of the most beneficial features. Ideally I'd like to be able to write the audio to a stream, and have multiple listeners that can manipulate the data. Right now I'm trying to read the file as a stream while it's being written, but not having much luck. Do you have a timeline for stream a implementation.

**Comment by Larpoux** [comment]
V6.0 is released. It supports Raw-PCM files (playback and record).

With this new version, we can also record Raw-PCM-LINEAR-16 to a Dart Stream or Playback PCM16 from a Dart Stream.
