### ISSUE TITLE
[HELP] Change audio frequency

### ISSUE THREAD

**Issue by FilipeOS** [dooboolab/flutter_sound#408]
Hi there,

Basically I'm trying to listen/play at same time to frequency between 2.35Hz and 2.5Hz.

How it would be possible to archive this?

I learned mainly Java but I'm trying to do both platforms that's why I'm using Flutter. Thank you!

**Comment by GGLabCenter** [comment]
+1: I am trying to achieve someting similar, but I don't know how to reach that. All the libraries for sound on flutter are about save audio to file and play audio from file, I think I'd need sometime on-the-fly, some open stream giving back constantly the byte arrays (maybe?), in order to be able to apply some manipulation (fft, maybe again)..

**Comment by GGLabCenter** [comment]
I just found something at least *near* to my problem: https://github.com/dooboolab/flutter_sound/issues/90
I'd say that the only thing is to access to the audio data itself while passing from the recorder to the player, in order to apply some filtering in the middle

**Comment by Larpoux** [comment]
I am not to understand fully your needs, but you could look to [this notice](https://github.com/dooboolab/flutter_sound/blob/master/flutter_sound/doc/codec.md#playing-pcm-16-from-a-dart-stream)

**Comment by Larpoux** [comment]
Please re-open this issue if you have still problems.
Actually I do not really understand your needs.
Probably it duplicates [#479]
