### ISSUE TITLE
[HELP] Record internal sound 

### ISSUE THREAD

**Issue by sukonin** [dooboolab/flutter_sound#419]
Hello guys, thank you for incredible plugging, but I'm looking for functionality, to record internal audio directly from device. Does it possible?

**Comment by Larpoux** [comment]
I am currently working on Flutter Sound V6.0 which will be released in next few weeks.
I hope to be able to stream the recording to a live Dart stream, both on Android and ios, with this new release.
Actually i am able to do that on Android, but not ios.
I hope to do able to do that before V6.0 release. So stay tuned.

**Comment by Larpoux** [comment]
V 6.0 is released. With this version you can record RAW-PCM-LINEAR-16 to a Dart Stream.
You can also playback a raw PCM from a Dart Stream

**Comment by ihorkozar** [comment]
@sukonin , did you find any solution?

**Comment by Larpoux** [comment]
@ihorkozar : what is exactly what you want to record ? Can you develop ?

**Comment by ihorkozar** [comment]
@Larpoux I want to record a call when the user is speaking using Google Meet or Zoom. I want to record audio not only from the microphone but also from the speaker

**Comment by Larpoux** [comment]
Oh, I see ...
Flutter Sound does not do anything for recording the device itself.
Perhaps you can have a look to [Audio Session](https://pub.dev/packages/audio_session) to see if it is possible to setup the input device as the device itself instead of the mic. I don't know very well this package but you may just look to it.
