### ISSUE TITLE
flutter_sound_lite: 4.0.5 How to switch speaker and earpiece

### ISSUE THREAD

**Issue by leielyq** [dooboolab/flutter_sound#437]
flutter_sound_lite: 4.0.5 How to switch speaker and earpiece。
It’s better to be compatible with earphone playback

**Comment by Larpoux** [comment]
When you call `openAudioSession()` you pass two parameters to specify on which device you want to playback (Bluetooth instead of loudspeaker).

Please look to the [API documentation](https://github.com/dooboolab/flutter_sound/blob/master/doc/player.md#openaudiosession-and-closeaudiosession).

Please re-open this issue if this answer does not satisfy you

**Comment by izht** [comment]
@Larpoux an V4's`openAudioSession` is `initialized` which didn't take any parameter, is this feature only available in v5?

**Comment by Larpoux** [comment]
Yes, this is a V5 feature.
V4 did not support any output device except "Speaker"

**Comment by leielyq** [comment]
@Larpoux 
 flutter_sound_lite: 6.3.1+1 
myPlayer.openAudioSession(
        device: AudioDevice.earPiece, audioFlags: allowBlueToothA2DP);
This does not work！！！sad。Please give me a demo

**Comment by leielyq** [comment]
Is there any Google service in flutter_inappwebview's js code that intercepts Ajax?
