### ISSUE TITLE
Convert iOS codebase to Swift

### ISSUE THREAD

**Issue by felixjunghans** [dooboolab/flutter_sound#465]
I would love to contribute more to Flutter Sound but the fact that the iOS code is written in Objective - C makes it very difficult. I think that this wonderful package might get more support if the iOS code was written in Swift. Personally, I found the switch from Dart to Swift extremely easy because the two languages are very similar. Kotlin and Swift are also very similar, which makes programming easier. I don't want to have a discussion about the basic principles, I just want to ask if it would be possible or maybe even planned for the future to convert the iOS codebase to Swift. I think that the package could gain even more contributors and make sure that it remains the best Flutter Sound package.

**Comment by Larpoux** [comment]
I Felix. This would be fantastic if you can contribute to Flutter Sound.
The problem of contributors is really dramatic.
@hyochan cannot work any more on Flutter Sound, and actually there is nobody to develop this product.
I contribute sometimes, but I will not have any spare time at the end of the year for working on Flutter Sound.
Without any developer, Flutter Sound will die soon, and it will be very bad because I think it is a great product.

For Swift, I am OK if someone develop with Swift, but personally I do not know anything about this language and I prefer not to learn an Apple specific language.
Objective-C is not an Apple language. I learnt and worked with Objective-C before the release of the first Macintosh, on an IBM-PC. Objective-C is very similar to C++ (with a Smalltalk syntax).
 
If you want to translate to Swift, go ahead, but I am very concerned by regressions. You will probably introduce many bugs.

**Comment by Larpoux** [comment]
This is same for Kotlin. I hate all those constructors and big companies who think intelligent to create new languages every 2 or 3 years.
Personally I will continue with Objective-C and Java.

**Comment by felixjunghans** [comment]
Okay. I thought you might feel that way. Anyway, I will try my best to find more time in the future to implement features in Flutter Sound.
