### ISSUE TITLE
Support for wave form

### ISSUE THREAD

**Issue by subhendukundu** [dooboolab/flutter_sound#513]
**Is your feature request related to a problem? Please describe.**

It's difficult to make real-time waves from an audio recorder such as Instagram.

**Describe the solution you'd like**

A method to get the wave data which we can pass plugin such as [flutter_visualizers](https://pub.dev/packages/flutter_visualizers).

**Describe alternatives you've considered**

I haven't found a workaround either.

**Comment by Larpoux** [comment]
Did you try to `startRecorder()` to a dart stream ?

**Comment by subhendukundu** [comment]
Yes!
I have it like
```
await recorder.startRecorder(
      codec: Codec.aacMP4,
      toFile: outputFile.path,
      sampleRate: 16000,
 );
```

**Comment by Larpoux** [comment]
You record to a file.
If I understand well, you want to get a Stream for sending the data to another plugin.
Instead of `toFile:`  you should use `toStream:` parameter.

Please [read this](https://github.com/dooboolab/flutter_sound/blob/master/flutter_sound/doc/codec.md#recording-pcm-16-to-a-dart-stream)

**Comment by subhendukundu** [comment]
Sure, Let me try it out.
Thanks

**Comment by Larpoux** [comment]
Please re-open if you have still problems
