### ISSUE TITLE
 why don‘t import the ffmpeg library with normal pose, it conflicts in ours projects ！！！

### ISSUE THREAD

**Issue by tryroach** [dooboolab/flutter_sound#541]
I need Help for :

- Using the API ?

- Generate an iOS or Android App ?

- Debugging my App ?

- Other ?

-------------------------------------

**Comment by Larpoux** [comment]
In version 3 (or maybe 4), flutter-FFmpeg was a regular dependency.
I do not remember exactly what was the problem, but Flutter Sound users had many problems because they had to adjust their Podfile, and build.gradle.
You are only the second people to complain about this way of doing the of link-edit. (The other guy needed to link with ffmpeg-video, and could not because of conflict). But in general, all Flutter Sound users are glad without having to adjust their Podifle/build.gradle.

If you have an idea how to solve that without bothering everybody, please tell us.

Note: I do not think that three exclamation points in the subject of your issue is appropriate.
