### ISSUE TITLE
Setup GitHub sponsors

### ISSUE THREAD

**Issue by gedw99** [dooboolab/flutter_sound#544]
Might be a good way to raise money.

**Comment by Larpoux** [comment]
Flutter Sound does not need money. It needs developers.
The main developers  do not work any more on Flutter Sound: 
- @hyochan 
- @salvatore373 
- @bsutton

I feel a little bit lonely. More, I will have to stop working on Flutter Sound soon because I have another project waiting for me : I will probably not be available during several month.

I have always been clear : I do not like to be the Flutter Sound project leader. I only do that because I do not want this project die. And I feel good when I think that my work is useful to other people.
